import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { PageHeader } from "@/components/app-shell";
import { Card } from "@/components/evidence";
import { generateStory, getMedia, getProjects, getTransformation } from "@/lib/api";
import type { Asset, Project } from "@/lib/demo-data";

export const Route = createFileRoute("/_workspace/story")({ component: Page });
function Page() {
  const [projects, setProjects] = useState<Project[]>([]);
  const [assets, setAssets] = useState<Asset[]>([]);
  const [projectId, setProjectId] = useState("");
  const [selected, setSelected] = useState<string[]>([]);
  const [story, setStory] = useState<any>();
  const [preview, setPreview] = useState(false);
  const [format, setFormat] = useState<"square" | "portrait" | "landscape">("square");
  const [transformed, setTransformed] = useState("");
  const [error, setError] = useState("");
  useEffect(() => { Promise.all([getProjects(), getMedia()]).then(([projectData, assetData]) => { setProjects(projectData); setAssets(assetData); const bestProject = projectData.find((project) => assetData.filter((asset) => asset.projectId === project.id).length >= 3) || projectData[0]; setProjectId(bestProject?.id || ""); }).catch((e: Error) => setError(e.message)); }, []);
  const projectAssets = assets.filter((asset) => asset.projectId === projectId);
  const selectedAssets = projectAssets.filter((asset) => selected.includes(asset.id));
  const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : current.length < 5 ? [...current, id] : current);
  async function create() { try { setError(""); setStory(await generateStory({ projectId, assetIds: selected, type: "impact_story" })); } catch (e) { setError(e instanceof Error ? e.message : "Unable to generate story"); } }
  async function makeFormat() { const source = selectedAssets[0]; if (!source) return; try { setError(""); const result = await getTransformation(source.id, format); setTransformed(result.transformedUrl); } catch (e) { setError(e instanceof Error ? e.message : "Unable to create Cloudinary format"); } }
  return <><PageHeader title="Story Studio" subtitle="Create an AI-assisted story from 3–5 persisted evidence assets. Every source remains linked and editable." />
    <div className="mb-6 flex flex-wrap items-center gap-3"><select value={projectId} onChange={(e) => { setProjectId(e.target.value); setSelected([]); setStory(undefined); }} className="rounded-md border bg-background px-3 py-2 text-sm">{projects.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select><span className="rounded-full bg-muted px-3 py-2 text-xs font-medium">{selected.length}/5 selected · minimum 3</span><button onClick={() => void create()} disabled={selected.length < 3} className="rounded-md bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-50">Generate AI-assisted draft</button></div>
    {error && <p className="mb-4 rounded-md border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{projectAssets.map((asset) => <button key={asset.id} onClick={() => toggle(asset.id)} className={`rounded-lg border p-2 text-left ${selected.includes(asset.id) ? "border-primary ring-2 ring-primary" : ""}`}>{asset.src ? <img src={asset.src} alt={asset.title} onError={(event) => { event.currentTarget.style.opacity = "0.35"; }} className="aspect-[4/3] w-full rounded object-cover" /> : <div className="aspect-[4/3] w-full rounded bg-muted flex items-center justify-center text-xs text-muted-foreground">No preview</div>}<span className="mt-2 block text-sm font-medium">{asset.title}</span><span className="block text-xs text-muted-foreground">{asset.date} · source evidence</span></button>)}</div>
    {story && <div className="mt-6 grid gap-6 lg:grid-cols-[1.3fr_0.7fr]"><Card title={`${story.title} · AI-assisted draft`} action={<button onClick={() => setPreview(!preview)} className="rounded-md border px-3 py-1.5 text-xs font-semibold">{preview ? "Edit story" : "Preview"}</button>}>{preview ? <article className="rounded-lg bg-muted p-5"><h2 className="font-display text-2xl">{story.title}</h2><p className="mt-4 whitespace-pre-wrap text-sm leading-6">{story.content}</p></article> : <div className="space-y-4"><label className="block text-sm font-medium">Headline<input value={story.title} onChange={(e) => setStory({ ...story, title: e.target.value })} className="mt-1 w-full rounded-md border bg-background p-2" /></label><label className="block text-sm font-medium">Story copy<textarea value={story.content} onChange={(e) => setStory({ ...story, content: e.target.value })} className="mt-1 min-h-52 w-full rounded-md border bg-background p-3 text-sm" /></label><p className="text-xs text-muted-foreground">Copy is based on selected metadata and visible observations. Review it before publishing; no unsupported metrics or outcomes are added.</p></div>}</Card>
      <Card title="Source evidence"><div className="space-y-3">{selectedAssets.map((asset) => <Link key={asset.id} to="/media/$id" params={{ id: asset.id }} className="flex items-center gap-3 rounded-lg border p-2 hover:bg-muted">{asset.src ? <img src={asset.src} alt="" className="h-12 w-16 rounded object-cover" /> : <div className="h-12 w-16 rounded bg-muted flex items-center justify-center text-xs text-muted-foreground">—</div>}<span className="text-sm">{asset.title}<span className="block text-xs text-muted-foreground">Open Evidence Passport</span></span></Link>)}</div><div className="mt-5 border-t pt-4"><h3 className="text-sm font-semibold">Cloudinary social format</h3><div className="mt-2 flex gap-2"><select value={format} onChange={(e) => setFormat(e.target.value as typeof format)} className="rounded-md border bg-background px-2 py-1.5 text-xs"><option value="square">Square</option><option value="portrait">Portrait 9:16</option><option value="landscape">Landscape 16:9</option></select><button onClick={() => void makeFormat()} className="rounded-md bg-secondary px-3 py-1.5 text-xs font-semibold">Generate format</button></div>{transformed && <a href={transformed} target="_blank" rel="noreferrer" className="mt-3 block text-xs text-primary underline">Open transformed Cloudinary asset</a>}</div></Card></div>}</>;
}
