/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as WorkspaceAnalyticsRouteImport } from './routes/_workspace.analytics'
import { Route as WorkspaceCompareRouteImport } from './routes/_workspace.compare'
import { Route as WorkspaceDashboardRouteImport } from './routes/_workspace.dashboard'
import { Route as WorkspaceNotificationsRouteImport } from './routes/_workspace.notifications'
import { Route as WorkspaceProjectsRouteImport } from './routes/_workspace.projects'
import { Route as WorkspaceReportsRouteImport } from './routes/_workspace.reports'
import { Route as WorkspaceSearchRouteImport } from './routes/_workspace.search'
import { Route as WorkspaceSettingsRouteImport } from './routes/_workspace.settings'
import { Route as WorkspaceStoryRouteImport } from './routes/_workspace.story'
import { Route as WorkspaceVerifyRouteImport } from './routes/_workspace.verify'
import { Route as WorkspaceMediaIndexRouteImport } from './routes/_workspace.media.index'
import { Route as WorkspaceMediaIdRouteImport } from './routes/_workspace.media.$id'
import { Route as WorkspaceProjectsIdRouteImport } from './routes/_workspace.projects.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceAnalyticsRoute = WorkspaceAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceCompareRoute = WorkspaceCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDashboardRoute = WorkspaceDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceNotificationsRoute = WorkspaceNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceProjectsRoute = WorkspaceProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceReportsRoute = WorkspaceReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSearchRoute = WorkspaceSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSettingsRoute = WorkspaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceStoryRoute = WorkspaceStoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceVerifyRoute = WorkspaceVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceMediaIndexRoute = WorkspaceMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceMediaIdRoute = WorkspaceMediaIdRouteImport.update({
  id: '/media/$id',
  path: '/media/$id',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceProjectsIdRoute = WorkspaceProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WorkspaceProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/analytics': typeof WorkspaceAnalyticsRoute
  '/compare': typeof WorkspaceCompareRoute
  '/dashboard': typeof WorkspaceDashboardRoute
  '/notifications': typeof WorkspaceNotificationsRoute
  '/projects': typeof WorkspaceProjectsRouteWithChildren
  '/reports': typeof WorkspaceReportsRoute
  '/search': typeof WorkspaceSearchRoute
  '/settings': typeof WorkspaceSettingsRoute
  '/story': typeof WorkspaceStoryRoute
  '/verify': typeof WorkspaceVerifyRoute
  '/media/$id': typeof WorkspaceMediaIdRoute
  '/projects/$id': typeof WorkspaceProjectsIdRoute
  '/media/': typeof WorkspaceMediaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/analytics': typeof WorkspaceAnalyticsRoute
  '/compare': typeof WorkspaceCompareRoute
  '/dashboard': typeof WorkspaceDashboardRoute
  '/notifications': typeof WorkspaceNotificationsRoute
  '/projects': typeof WorkspaceProjectsRouteWithChildren
  '/reports': typeof WorkspaceReportsRoute
  '/search': typeof WorkspaceSearchRoute
  '/settings': typeof WorkspaceSettingsRoute
  '/story': typeof WorkspaceStoryRoute
  '/verify': typeof WorkspaceVerifyRoute
  '/media/$id': typeof WorkspaceMediaIdRoute
  '/projects/$id': typeof WorkspaceProjectsIdRoute
  '/media': typeof WorkspaceMediaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_workspace/analytics': typeof WorkspaceAnalyticsRoute
  '/_workspace/compare': typeof WorkspaceCompareRoute
  '/_workspace/dashboard': typeof WorkspaceDashboardRoute
  '/_workspace/notifications': typeof WorkspaceNotificationsRoute
  '/_workspace/projects': typeof WorkspaceProjectsRouteWithChildren
  '/_workspace/reports': typeof WorkspaceReportsRoute
  '/_workspace/search': typeof WorkspaceSearchRoute
  '/_workspace/settings': typeof WorkspaceSettingsRoute
  '/_workspace/story': typeof WorkspaceStoryRoute
  '/_workspace/verify': typeof WorkspaceVerifyRoute
  '/_workspace/media/$id': typeof WorkspaceMediaIdRoute
  '/_workspace/projects/$id': typeof WorkspaceProjectsIdRoute
  '/_workspace/media/': typeof WorkspaceMediaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/analytics'
    | '/compare'
    | '/dashboard'
    | '/notifications'
    | '/projects'
    | '/reports'
    | '/search'
    | '/settings'
    | '/story'
    | '/verify'
    | '/media/$id'
    | '/projects/$id'
    | '/media/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/analytics'
    | '/compare'
    | '/dashboard'
    | '/notifications'
    | '/projects'
    | '/reports'
    | '/search'
    | '/settings'
    | '/story'
    | '/verify'
    | '/media/$id'
    | '/projects/$id'
    | '/media'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/login'
    | '/onboarding'
    | '/_workspace/analytics'
    | '/_workspace/compare'
    | '/_workspace/dashboard'
    | '/_workspace/notifications'
    | '/_workspace/projects'
    | '/_workspace/reports'
    | '/_workspace/search'
    | '/_workspace/settings'
    | '/_workspace/story'
    | '/_workspace/verify'
    | '/_workspace/media/$id'
    | '/_workspace/projects/$id'
    | '/_workspace/media/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/analytics': {
      id: '/_workspace/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof WorkspaceAnalyticsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/compare': {
      id: '/_workspace/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof WorkspaceCompareRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/dashboard': {
      id: '/_workspace/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof WorkspaceDashboardRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/notifications': {
      id: '/_workspace/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof WorkspaceNotificationsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/projects': {
      id: '/_workspace/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof WorkspaceProjectsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/reports': {
      id: '/_workspace/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof WorkspaceReportsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/search': {
      id: '/_workspace/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof WorkspaceSearchRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/settings': {
      id: '/_workspace/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/story': {
      id: '/_workspace/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof WorkspaceStoryRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/verify': {
      id: '/_workspace/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof WorkspaceVerifyRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/media/': {
      id: '/_workspace/media/'
      path: '/media'
      fullPath: '/media/'
      preLoaderRoute: typeof WorkspaceMediaIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/media/$id': {
      id: '/_workspace/media/$id'
      path: '/media/$id'
      fullPath: '/media/$id'
      preLoaderRoute: typeof WorkspaceMediaIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/projects/$id': {
      id: '/_workspace/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof WorkspaceProjectsIdRouteImport
      parentRoute: typeof WorkspaceProjectsRoute
    }
  }
}

interface WorkspaceProjectsRouteChildren {
  WorkspaceProjectsIdRoute: typeof WorkspaceProjectsIdRoute
}

const WorkspaceProjectsRouteChildren: WorkspaceProjectsRouteChildren = {
  WorkspaceProjectsIdRoute: WorkspaceProjectsIdRoute,
}

const WorkspaceProjectsRouteWithChildren =
  WorkspaceProjectsRoute._addFileChildren(WorkspaceProjectsRouteChildren)

interface WorkspaceRouteChildren {
  WorkspaceAnalyticsRoute: typeof WorkspaceAnalyticsRoute
  WorkspaceCompareRoute: typeof WorkspaceCompareRoute
  WorkspaceDashboardRoute: typeof WorkspaceDashboardRoute
  WorkspaceNotificationsRoute: typeof WorkspaceNotificationsRoute
  WorkspaceProjectsRoute: typeof WorkspaceProjectsRouteWithChildren
  WorkspaceReportsRoute: typeof WorkspaceReportsRoute
  WorkspaceSearchRoute: typeof WorkspaceSearchRoute
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRoute
  WorkspaceStoryRoute: typeof WorkspaceStoryRoute
  WorkspaceVerifyRoute: typeof WorkspaceVerifyRoute
  WorkspaceMediaIdRoute: typeof WorkspaceMediaIdRoute
  WorkspaceMediaIndexRoute: typeof WorkspaceMediaIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceAnalyticsRoute: WorkspaceAnalyticsRoute,
  WorkspaceCompareRoute: WorkspaceCompareRoute,
  WorkspaceDashboardRoute: WorkspaceDashboardRoute,
  WorkspaceNotificationsRoute: WorkspaceNotificationsRoute,
  WorkspaceProjectsRoute: WorkspaceProjectsRouteWithChildren,
  WorkspaceReportsRoute: WorkspaceReportsRoute,
  WorkspaceSearchRoute: WorkspaceSearchRoute,
  WorkspaceSettingsRoute: WorkspaceSettingsRoute,
  WorkspaceStoryRoute: WorkspaceStoryRoute,
  WorkspaceVerifyRoute: WorkspaceVerifyRoute,
  WorkspaceMediaIdRoute: WorkspaceMediaIdRoute,
  WorkspaceMediaIndexRoute: WorkspaceMediaIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
